### PR TITLE
device-reminder user warning

### PR DESCRIPTION
**Pull request by Xenon-s**
Special procedure after update to versions as of 1.2.x

### CODE REVIEW

**Comment by Apollon77** [comment]
Please add the adatername also in title, so that user can see that in first view

**Comment by Apollon77** [comment]
is the 1.2.1 stable oder latest?

**Comment by Xenon-s** [comment]
Latest. I had completely converted the adapter structure to classes and therefore had to make adjustments in the Index_m. That's why the user has to click on "Save and close" once, so that the data gets into the native in the new format.

**Comment by Apollon77** [comment]
Then you should also add the repo because else all users get the message but can not see that version

**Comment by Xenon-s** [comment]
But it will probably be the stable version in a few days? Then these users must also know that

**Comment by Apollon77** [comment]
then you can change the info as new PR :-)

**Comment by Xenon-s** [comment]
And which version should I specify in the PR?

**Comment by Apollon77** [comment]
No, you just add 

```
"repo": "latest"
```

**Comment by Xenon-s** [comment]
"conditions": {
            "device-reminder": "smaller(1.2.1)",
            "repo": "latest"
        }

You mean like this?

**Comment by Xenon-s** [comment]
You mean like this?

"id": "device-reminder-update-1-2-x",
        "class": "warn",
        "fa-icon": "exclamation-triangle",
        "created": "2021-05-02T01:00:00.000Z",
        "repo": "latest"
        "conditions": {
            "device-reminder": "smaller(1.2.1)"
        }

**Comment by Apollon77** [comment]
Ithink so ... compare to other entries in the file :-)

**Comment by Xenon-s** [comment]
Apparently I'm the first one so far. No one has given a repo until now ;P

**Pull request merged**
