### PR TITLE
Clarify that array, object and mixed must be serialized

### PR DESCRIPTION
**Pull request by UncleSamSwiss**

### CODE REVIEW

**Comment by UncleSamSwiss** [comment]
One uncertainty:
Do we support "json" as type?
In the type definitions it is not allowed:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/25a17e04a81dd5bb9b97b3cec89d14af45926674/types/iobroker/objects.d.ts#L136
In the js-controller we allow it:
https://github.com/ioBroker/ioBroker.js-controller/blob/b6e11963a3a32b9757396767677375ac93fa62a9/lib/adapter.js#L1761

@AlCalzone @Apollon77

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.js-controller/blob/b6e11963a3a32b9757396767677375ac93fa62a9/lib/tools.js#L2114 ... from my perspective this is the offical list we use checking on code, so we would need to adfjust the types definition

**Comment by Apollon77** [comment]
And value when type is "File" also needs to be a string

**Comment by Garfonso** [comment]
I think the file part is a bit misleading. For me it sounds like a Json stringified version of the file content is required. Is this right?
or is it just the file path as string?

**Comment by UncleSamSwiss** [comment]
Can somebody please provide a clarification for the "file" type. I have no clue what it should be as I have never used files before.
@Garfonso or @Apollon77 ?

**Comment by Garfonso** [comment]
I didn't use file yet and don't really know what it expects... we should make that clear in the documentation.

**Comment by UncleSamSwiss** [comment]
Perhaps @AlCalzone may be able to provide a meaningful text?

**Comment by AlCalzone** [comment]
I don't use the `file` object type either 🤷🏻‍♂️

**Comment by GermanBluefox** [comment]
File is a special state.
Its content must be written wirh `adapter.setBinaryState` and it does not have ack, user, from, quality or comment attributes.
So for files there is no type. It is always Buffer and you cannot use `adapter.setState` for that.

**Pull request merged**
