### PR TITLE
Update news.json - deprecate INFO adapter

### PR DESCRIPTION
**Pull request by mcm1957**
@Apollon77

### CODE REVIEW

**Comment by Apollon77** [comment]
Do we need to use such a drastic text?
I would go with "WIll not receive any updates and might stop working in future jsöcintroller versions" or such ... Additionally you have a JSON error

**Comment by mcm1957** [comment]
OK for me too.
I'll check json

**Comment by mcm1957** [comment]
@Apollon77 

Text changed to
'Adapter ioBroker.info is deprecated now. The adapter will not receive any updates and might stop working correctly in future.'

I would prefer not to mention js-controller as malfunction might arise because of several issues. I.e. news role seems to be broke in parts already and there might be upcoming incompatibilities i.e. with license varaibles. Such cases are not related to js.controller. Please check and feel free to modify further. But I do not want to suggest that info continuers to work with js-controller5. If you prefer we could shorten to
'Adapter ioBroker.info is deprecated now. The adapter will not receive any updates.'

json syntax should be ok now. Sorry for breaking this.

**Comment by Apollon77** [comment]
Thank you

**Pull request merged**
