### PR TITLE
Fix table layout

### PR DESCRIPTION
**Pull request by SkyLined**
The table layout was broken and has been fixed.

This was initially detected in the "en" version but that file said it was automatically translated from this page, so I believe making the changes in this file will fix both (assuming the new "de" version is automatically translated after this patch is committed)

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you!

**Comment by SkyLined** [comment]
How long until this change affects the `en` version at https://www.iobroker.net/#en/documentation/install/requirements.md?

**Comment by Apollon77** [comment]
That might take a week. I can ask @GermanBluefox to update manually

**Comment by SkyLined** [comment]
No hurry, I'm new and just wanted to know. Also, I expected it to be quicker and wanted to make sure it wasn't broken.

**Pull request merged**
