### PR TITLE
Update news.md

### PR DESCRIPTION
**Pull request by ldittmar81**

### CODE REVIEW

**Comment by Apollon77** [comment]
Merge Pending decisions around Admin-PR merge

**Comment by GermanBluefox** [comment]
Please no UUID in clear text here, only hashes

**Comment by ldittmar81** [comment]
> Please no UUID in clear text here, only hashes

We use a SHA1 Hash to do this

**Comment by ldittmar81** [comment]
@GermanBluefox was genau meinst du? Ich verstehe es nicht...

**Comment by ldittmar81** [comment]
It uses SHA256 now

**Pull request merged**
